apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "3"
      field.cattle.io/creatorId: u-n27hq
      field.cattle.io/publicEndpoints: '[{"addresses":["10.3.0.11"],"port":443,"protocol":"HTTPS","serviceName":"cicd-example:ingress-a7954997f3214ab6da03d0b8de8be288","ingressName":"cicd-example:atrium-staging.unicef.io","hostname":"atrium-staging.unicef.io","path":"/","allNodes":true},{"nodeName":"c-jczzj:m-40f63633b95d","addresses":["10.3.0.19"],"port":4000,"protocol":"TCP","podName":"cicd-example:cicd-5c87f9c59-lt5qh","allNodes":false}]'
    creationTimestamp: "2020-03-23T17:08:01Z"
    generation: 7
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-cicd-example-cicd
    name: cicd
    namespace: cicd-example
    resourceVersion: "57651308"
    selfLink: /apis/apps/v1/namespaces/cicd-example/deployments/cicd
    uid: acc002bb-f933-48a7-a94e-362a2f7ca7da
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-cicd-example-cicd
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: "2020-03-23T17:26:48Z"
          field.cattle.io/ports: '[[{"containerPort":4000,"dnsName":"cicd-hostport","hostPort":4000,"kind":"HostPort","name":"tcp4000","protocol":"TCP","sourcePort":4000}]]'
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-cicd-example-cicd
      spec:
        containers:
        - image: asherbuck/cicd
          imagePullPolicy: Always
          name: cicd
          ports:
          - containerPort: 4000
            hostPort: 4000
            name: tcp4000
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2020-03-23T17:10:17Z"
      lastUpdateTime: "2020-03-23T17:10:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2020-03-23T17:08:01Z"
      lastUpdateTime: "2020-03-23T17:26:54Z"
      message: ReplicaSet "cicd-5c87f9c59" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 7
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List

