apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd
  labels:
    app: cicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: cicd
          image: asherbuck/cicd:latest
          ports:
            - containerPort: 4000
